In [1]:
from perceptron import Perceptron
from adaline import ADALINE

In [2]:
import style
style.apply()

In [3]:
# Datos de entrada 
S = [[1, 3],
     [3, 3],
     [1, 1],
     [3, 1],
     [-2, -1],
     [-1, -2]]

T = [1, -1, -1, -1, 1, 1]  # Salidas esperadas

In [4]:
# Crear y entrenar el perceptrón
perceptron = Perceptron(S, T, learning_rate=0.05, epochs=10, umbral=0.5)
perceptron.fit()
# perceptron.plot()

In [5]:
perceptron.get_bias()

[np.float64(0.05),
 np.float64(0.0),
 np.float64(-0.05),
 np.float64(-0.05),
 np.float64(0.0),
 np.float64(0.05),
 np.float64(0.1),
 np.float64(0.1),
 np.float64(0.05),
 np.float64(0.05),
 np.float64(0.05),
 np.float64(0.05)]

In [6]:
perceptron.get_weights()

[array([0.05, 0.15]),
 array([-0.1,  0. ]),
 array([-0.15, -0.05]),
 array([-0.15, -0.05]),
 array([-0.25, -0.1 ]),
 array([-0.3, -0.2]),
 array([-0.25, -0.05]),
 array([-0.25, -0.05]),
 array([-0.3, -0.1]),
 array([-0.3, -0.1]),
 array([-0.3, -0.1]),
 array([-0.3, -0.1])]

In [7]:
malos = perceptron.get_malos()  # Número de clasificaciones incorrectas

In [8]:
malos[6]

[{'coords': array([1, 3]),
  'target': 1,
  'valor': -0.8500000000000001,
  'y': -1.0},
 {'coords': array([1, 1]),
  'target': -1,
  'valor': -0.19999999999999998,
  'y': 0.0}]

In [9]:
len(malos[6]) #  número de datos mal clasificados en cada iteración

2

In [5]:
perceptron.plot()

In [14]:
adaline = ADALINE(S, T, learning_rate=0.0001, epochs=1, umbral=0.1, tolerance=1e-16)
adaline.fit()
#adaline.plot()

In [15]:
adaline.get_bias()

[np.float64(0.0001),
 np.float64(0.0),
 np.float64(-0.0001),
 np.float64(-0.0002),
 np.float64(-0.0001),
 np.float64(0.0)]

In [16]:
adaline.get_weights()

[array([0.0001, 0.0003]),
 array([-0.0002,  0.    ]),
 array([-0.0003, -0.0001]),
 array([-0.0006, -0.0002]),
 array([-0.0008, -0.0003]),
 array([-0.0009, -0.0005])]

In [18]:
adaline_malos = adaline.get_malos()
adaline_malos[0]  # Datos mal clasificados en la primera iteración

[{'coords': array([1, 3]), 'target': 1, 'valor': 0.0, 'y': 0.0},
 {'coords': array([3, 3]),
  'target': -1,
  'valor': 0.0013000000000000002,
  'y': 0.0},
 {'coords': array([1, 1]),
  'target': -1,
  'valor': -0.00020000000000000004,
  'y': 0.0},
 {'coords': array([3, 1]), 'target': -1, 'valor': -0.0011, 'y': 0.0},
 {'coords': array([-2, -1]),
  'target': 1,
  'valor': 0.0012000000000000001,
  'y': 0.0},
 {'coords': array([-1, -2]),
  'target': 1,
  'valor': 0.0013000000000000002,
  'y': 0.0}]

In [19]:
len(adaline_malos[0])  # número de datos mal clasificados en la primera iteración

6