In [35]:
from perceptron import Perceptron
from adaline import ADALINE

In [36]:
import style
style.mpl_apply()

In [37]:
# Datos de entrada 
AND = [[1, 1],
     [0, 1],
     [1, 0],
     [0, 0]]

T = [1, -1, -1, -1]  # Salidas esperadas

In [43]:
# Crear y entrenar el perceptrón
perceptron = Perceptron(AND, T, learning_rate=0.1, epochs=30, umbral=0.01, weights=[0.5, 0.5], bias=0.5)
perceptron.fit()
perceptron.plot()

In [40]:
perceptron.get_bias()

[np.float64(0.001),
 np.float64(0.0),
 np.float64(-0.001),
 np.float64(-0.002),
 np.float64(-0.001),
 np.float64(-0.002),
 np.float64(-0.003),
 np.float64(-0.004),
 np.float64(-0.003),
 np.float64(-0.004),
 np.float64(-0.005),
 np.float64(-0.006),
 np.float64(-0.005),
 np.float64(-0.006),
 np.float64(-0.007),
 np.float64(-0.008),
 np.float64(-0.007),
 np.float64(-0.008),
 np.float64(-0.009000000000000001),
 np.float64(-0.010000000000000002),
 np.float64(-0.009000000000000001),
 np.float64(-0.010000000000000002),
 np.float64(-0.011000000000000003),
 np.float64(-0.011000000000000003)]

In [26]:
perceptron.get_weights()

[array([-0.01, -0.03]),
 array([-0.01, -0.03]),
 array([-0.01, -0.03]),
 array([-0.01, -0.03]),
 array([-0.01, -0.03]),
 array([-0.01, -0.03])]

In [27]:
patrones_que_hicieron_que_ajustara = perceptron.get_malos()  # Número de clasificaciones incorrectas

In [28]:
patrones_que_hicieron_que_ajustara

[[{'coords': array([1, 3]), 'target': -1, 'valor': 0.0, 'y': 0.0}],
 [{'coords': array([1, 3]), 'target': -1, 'valor': 0.0, 'y': 0.0}],
 [{'coords': array([1, 3]), 'target': -1, 'valor': 0.0, 'y': 0.0}],
 [{'coords': array([1, 3]), 'target': -1, 'valor': 0.0, 'y': 0.0}],
 [{'coords': array([1, 3]), 'target': -1, 'valor': 0.0, 'y': 0.0}],
 [{'coords': array([1, 3]), 'target': -1, 'valor': 0.0, 'y': 0.0}]]

In [29]:
len(patrones_que_hicieron_que_ajustara) #  número de iteraciones realizadas

6

In [30]:
len(patrones_que_hicieron_que_ajustara[2]) #  número de datos mal clasificados la 

1

In [31]:
malos_por_iteracion = perceptron.get_malos_por_iteracion()
malos_por_iteracion

[0, 0, 0, 0, 0, 0]

In [32]:
len(malos_por_iteracion)

6

In [33]:
patrones_que_hicieron_que_ajustara[0]

[{'coords': array([1, 3]), 'target': -1, 'valor': 0.0, 'y': 0.0}]

In [34]:
perceptron.plot()

In [47]:
# Datos de entrada 
XOR = [[1, 1],
     [0, 1],
     [1, 0],
     [0, 0]]

T = [1, -1, -1, 1]  # Salidas esperadas

# Crear y entrenar el perceptrón
perceptron = Perceptron(XOR, T, learning_rate=0.1, epochs=30, umbral=0.01, weights=[1, 1], bias=-0.5)
perceptron.fit()
perceptron.plot()

In [14]:
adaline = ADALINE(S, T, learning_rate=0.0001, epochs=1, umbral=0.1, tolerance=1e-16)
adaline.fit()
#adaline.plot()

In [15]:
adaline.get_bias()

[np.float64(0.0001),
 np.float64(0.0),
 np.float64(-0.0001),
 np.float64(-0.0002),
 np.float64(-0.0001),
 np.float64(0.0)]

In [16]:
adaline.get_weights()

[array([0.0001, 0.0003]),
 array([-0.0002,  0.    ]),
 array([-0.0003, -0.0001]),
 array([-0.0006, -0.0002]),
 array([-0.0008, -0.0003]),
 array([-0.0009, -0.0005])]

In [18]:
adaline_malos = adaline.get_malos()
adaline_malos[0]  # Datos mal clasificados en la primera iteración

[{'coords': array([1, 3]), 'target': 1, 'valor': 0.0, 'y': 0.0},
 {'coords': array([3, 3]),
  'target': -1,
  'valor': 0.0013000000000000002,
  'y': 0.0},
 {'coords': array([1, 1]),
  'target': -1,
  'valor': -0.00020000000000000004,
  'y': 0.0},
 {'coords': array([3, 1]), 'target': -1, 'valor': -0.0011, 'y': 0.0},
 {'coords': array([-2, -1]),
  'target': 1,
  'valor': 0.0012000000000000001,
  'y': 0.0},
 {'coords': array([-1, -2]),
  'target': 1,
  'valor': 0.0013000000000000002,
  'y': 0.0}]

In [19]:
len(adaline_malos[0])  # número de datos mal clasificados en la primera iteración

6