In [1]:
from perceptron import Perceptron
from adaline import ADALINE

In [2]:
# Datos de entrada 
S = [[1, 3],
     [3, 3],
     [1, 1],
     [3, 1],
     [-2, -1],
     [-1, -2]]

T = [1, -1, -1, -1, 1, 1]  # Salidas esperadas

In [3]:
# Crear y entrenar el perceptrón
perceptron = Perceptron(S, T, learning_rate=0.05, epochs=10, umbral=0.5)
perceptron.fit()
# perceptron.plot()

In [4]:
perceptron.get_bias()

[np.float64(0.05),
 np.float64(0.0),
 np.float64(-0.05),
 np.float64(-0.05),
 np.float64(0.0),
 np.float64(0.05),
 np.float64(0.1),
 np.float64(0.1),
 np.float64(0.05),
 np.float64(0.05),
 np.float64(0.05),
 np.float64(0.05)]

In [5]:
perceptron.get_weights()

[array([0.05, 0.15]),
 array([-0.1,  0. ]),
 array([-0.15, -0.05]),
 array([-0.15, -0.05]),
 array([-0.25, -0.1 ]),
 array([-0.3, -0.2]),
 array([-0.25, -0.05]),
 array([-0.25, -0.05]),
 array([-0.3, -0.1]),
 array([-0.3, -0.1]),
 array([-0.3, -0.1]),
 array([-0.3, -0.1])]

In [7]:
malos = perceptron.get_malos()  # Número de clasificaciones incorrectas

In [8]:
malos[0]

[{'coords': array([1, 3]),
  'target': np.int64(1),
  'valor': np.float64(0.0),
  'y': 0.0},
 {'coords': array([3, 3]),
  'target': np.int64(-1),
  'valor': np.float64(0.6500000000000001),
  'y': 1.0},
 {'coords': array([1, 1]),
  'target': np.int64(-1),
  'valor': np.float64(-0.10000000000000002),
  'y': 0.0},
 {'coords': array([-2, -1]),
  'target': np.int64(1),
  'valor': np.float64(0.30000000000000004),
  'y': 0.0},
 {'coords': array([-1, -2]),
  'target': np.int64(1),
  'valor': np.float64(0.45),
  'y': 0.0}]

In [ ]:
adaline = ADALINE(S, T, learning_rate=0.0001, epochs=10, umbral=0.1, tolerance=1e-16)
adaline.fit()
adaline.plot()