In [1]:
import torch

c:\Users\herie\miniconda3\envs\dl\Lib\site-packages\torch\_subclasses\functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


# Introduction to PyTorch, a Deep Learning Library

Self-driving cars, smartphones, search engines... Deep learning is now everywhere. Before you begin building complex models, you will become familiar with PyTorch, a deep learning framework. You will learn how to manipulate tensors, create PyTorch data structures, and build your first neural network in PyTorch with linear layers.

## Getting started with PyTorch tensors
Tensors are PyTorch's core data structure and the foundation of deep learning. They're similar to NumPy arrays but have unique features.

Here you have a Python list named temperatures containing daily readings from two weather stations. Try converting this into a tensor!

Instructions
100 XP
Begin by importing torch.
Create a tensor from the Python list temperatures.

In [2]:
temperatures = [[72, 75, 78], [70, 73, 76]]

# Create a tensor from temperatures
temp_tensor = torch.tensor(temperatures)

print(temp_tensor)

tensor([[72, 75, 78],
        [70, 73, 76]])


## Checking and adding tensors
While collecting temperature data, you notice the readings are off by two degrees. Add two degrees to the temperatures tensor after verifying its shape and data type with torch to ensure compatibility with the adjustment tensor.

The torch library and the temperatures tensor are loaded for you.

Instructions 1/2
50 XP
Display the shape of the adjustment tensor.
Display the data type of the adjustment tensor.

In [11]:
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])

# Display the adjustment tensor
print("Adjustment tensor:", adjustment)

# Display the shape of the adjustment tensor
print("Adjustment shape:", adjustment.shape)

# Display the type of the adjustment tensor
print("Adjustment type:", adjustment.dtype)

print("\n")
print("Temperatures tensor:", temp_tensor)
print("Temperatures shape:", temp_tensor.shape)
print("Temperatures type:", temp_tensor.dtype)

Adjustment tensor: tensor([[2, 2, 2],
        [2, 2, 2]])
Adjustment shape: torch.Size([2, 3])
Adjustment type: torch.int64


Temperatures tensor: tensor([[72, 75, 78],
        [70, 73, 76]])
Temperatures shape: torch.Size([2, 3])
Temperatures type: torch.int64


Add the temperatures and adjustment tensors.

In [10]:
# Add the temperatures and adjustment tensors
corrected_temperatures = temp_tensor + adjustment
print("Corrected temperatures:", corrected_temperatures)

Corrected temperatures: tensor([[74, 77, 80],
        [72, 75, 78]])


## Linear layer network
Neural networks often contain many layers, but most of them are linear layers. Understanding a single linear layer helps you grasp how they work before adding complexity.

Apply a linear layer to an input tensor and observe the output.

Instructions
100 XP
Create a Linear layer that takes 3 features as input and returns 2 outputs.
Pass input_tensor through the linear laye

In [12]:
import torch.nn as nn

input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

# Create a Linear layer
linear_layer = nn.Linear(
                         in_features=3, 
                         out_features=2
                         )

# Pass input_tensor through the linear layer
output = linear_layer(input_tensor)

print(output)

tensor([[-0.0474, -0.3546]], grad_fn=<AddmmBackward0>)


## Your first neural network
It's time for you to implement a small neural network containing two linear layers in sequence.

Instructions
100 XP
Add a container for stacking layers in sequence.

In [13]:
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Create a container for stacking linear layers
model = nn.Sequential(nn.Linear(8, 4),
                nn.Linear(4, 1)
                )

output = model(input_tensor)
print(output)

tensor([[-5.1217]], grad_fn=<AddmmBackward0>)


## Counting the number of parameters
Deep learning models are famous for having a lot of parameters. With more parameters comes more computational complexity and longer training times, and a deep learning practitioner must know how many parameters their model has.

In this exercise, you'll first calculate the number of parameters manually. Then, you'll verify your result using the .numel() method.

Instructions 1/2
50 XP
Question
Manually calculate the number of parameters of the model below. How many does it have? Use the console as a calculator.

model = nn.Sequential(nn.Linear(9, 4),
                      nn.Linear(4, 2),
                      nn.Linear(2, 1))

answer = 53

In [14]:
(9 + 1)*4 + (4 + 1)*2 + (2 + 1)*1

53

Use .numel() to confirm your manual calculation by iterating through the model's parameters to updating the total variable.

In [15]:
model = nn.Sequential(nn.Linear(9, 4),
                      nn.Linear(4, 2),
                      nn.Linear(2, 1))

total = 0

# Calculate the number of parameters in the model
for p in model.parameters():
  total += p.numel()
  
print(f"The number of parameters in the model is {total}")

The number of parameters in the model is 53


# Neural Network Architecture and Hyperparameters

To train a neural network in PyTorch, you will first need to understand additional components, such as activation and loss functions. You will then realize that training a network requires minimizing that loss function, which is done by calculating gradients. You will learn how to use these gradients to update your model's parameters.

## The sigmoid and softmax functions
The sigmoid and softmax functions are key activation functions in deep learning, often used as the final step in a neural network.

Sigmoid is for binary classification
Softmax is for multi-class classification
Given a pre-activation output tensor from a network, apply the appropriate activation function to obtain the final output.

Create a sigmoid function and apply it on input_tensor to generate a probability for a binary classification task.

In [ ]:
# Create a sigmoid function and apply it on input_tensor
input_tensor = torch.tensor([[2.4]])
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

tensor([[0.9168]])


Create a softmax function and apply it on input_tensor to generate a probability for a multi-class classification task.

In [ ]:
# Create a softmax function and apply it on input_tensor
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])
softmax = nn.Softmax(dim=1)
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


## From regression to multi-class classification
The models you have seen for binary classification, multi-class classification and regression have all been similar, barring a few tweaks to the model.


Start building a model for regression, and then tweak the model to perform a multi-class classification.

In [18]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
    nn.Linear(11, 8),
    nn.Linear(8, 4),
    nn.Linear(4, 2),
    nn.Linear(2, 1)
)

output = model(input_tensor)
print(output)
# tensor([[-0.6931]], grad_fn=<AddmmBackward0>)
# This means the model 

tensor([[-0.1464]], grad_fn=<AddmmBackward0>)


Create a 4-layer linear network that takes 11 input features from input_tensor and produces a single regression output.Update the network provided to perform a multi-class classification with four outputs

In [19]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4),
  nn.Softmax(dim=1)  # Softmax activation for multi-class classification
  # dim = 1 indicates that softmax is applied across the columns (i.e., across the classes), dim = 0 would apply it across rows (i.e., across samples) dim = 2 is for 3D tensors
)

output = model(input_tensor)
print(output)
# tensor([[0.0272, 0.2199, 0.2299, 0.5230]], grad_fn=<SoftmaxBackward0>)

tensor([[0.1829, 0.2071, 0.4391, 0.1709]], grad_fn=<SoftmaxBackward0>)


## Creating one-hot encoded labels
One-hot encoding converts a single integer label into a vector with N elements, where N is the number of classes. This vector contains zeros and a one at the correct position.

In this exercise, you'll manually create a one-hot encoded vector for y, and then use PyTorch to simplify the process. Your dataset has three classes (0, 1, 2).

numpy (np), torch.nn.functional (F), and torch are already imported for you.


Manually one-hot encode the ground truth label y using the provided NumPy array and save it as one_hot_numpy.
Use PyTorch to one-hot encode y and save it as one_hot_pytorch.

In [22]:
import numpy as np
import torch.nn.functional as F

y = 1
num_classes = 3

# Create the one-hot encoded vector using NumPy
one_hot_numpy = np.array([0, 1, 0])  # Manually create the one-hot vector

# Create the one-hot encoded vector using PyTorch
one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes=num_classes)

print("One-hot vector using NumPy:", one_hot_numpy)
print("One-hot vector using PyTorch:", one_hot_pytorch)

One-hot vector using NumPy: [0 1 0]
One-hot vector using PyTorch: tensor([0, 1, 0])


## Calculating cross entropy loss
Cross-entropy loss is a widely used method to measure classification loss. In this exercise, you’ll calculate cross-entropy loss in PyTorch using:

y: the ground truth label.
scores: a vector of predictions before softmax.
Loss functions help neural networks learn by measuring prediction errors. Create a one-hot encoded vector for y, define the cross-entropy loss function, and compute the loss using scores and the encoded label. The result will be a single float representing the sample's loss.

torch, CrossEntropyLoss, and torch.nn.functional as F have already been imported for you.


Create the one-hot encoded vector of the ground truth label y, with 4 features (one for each class), and assign it to one_hot_label.

In [23]:
y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), num_classes=4)

Create the cross entropy loss function and store it as criterion.

In [24]:
from torch.nn import CrossEntropyLoss

# Define the cross-entropy loss function
criterion = CrossEntropyLoss()

Calculate the cross entropy loss using the one_hot_label vector and the scores vector, by calling the loss_function you created.

In [25]:
# Calculate the cross entropy loss
loss = criterion(scores.double(), one_hot_label.double())
print(loss)

tensor(8.0619, dtype=torch.float64)


## Accessing the model parameters
A PyTorch model created with the nn.Sequential() is a module that contains the different layers of your network. Recall that each layer parameter can be accessed by indexing the created model directly. In this exercise, you will practice accessing the parameters of different linear layers of a neural network.

Instructions
100 XP
Access the weight parameter of the first linear layer.

In [28]:
model = nn.Sequential(nn.Linear(16, 8),
                      nn.Linear(8, 4),
                      nn.Linear(4, 2),
                     )
    
# Access the weight of the first linear layer
weight_0 = model[0].weight
print("Weight of the first layer:", weight_0)

# Access the bias of the second linear layer
bias_1 = model[1].bias
print("Bias of the second layer:", bias_1)

Weight of the first layer: Parameter containing:
tensor([[-0.2160, -0.0904,  0.1235, -0.1414, -0.1022,  0.0004,  0.0353, -0.1649,
          0.0540, -0.1548,  0.1601,  0.1101, -0.1018, -0.0209,  0.0311,  0.1832],
        [ 0.2224,  0.1088, -0.1695, -0.1489,  0.0010, -0.1600,  0.0307,  0.2181,
         -0.0660,  0.2083,  0.1133,  0.1727, -0.1298,  0.0562,  0.1684,  0.0335],
        [-0.1897,  0.0661, -0.0109,  0.2298,  0.0788, -0.0005,  0.1207,  0.2481,
         -0.0005, -0.0042, -0.0036, -0.1985,  0.1357,  0.0016, -0.1460,  0.0266],
        [ 0.0488, -0.1098, -0.1646,  0.1847, -0.1431, -0.1599, -0.0886, -0.1076,
          0.0440, -0.0592, -0.1800,  0.2356,  0.0498, -0.1185,  0.0075, -0.2016],
        [-0.0415,  0.2378, -0.1401, -0.1166, -0.0523,  0.2317,  0.0627, -0.0379,
          0.1643,  0.2266,  0.0198,  0.0575, -0.0330, -0.1573,  0.0964, -0.0189],
        [-0.1151,  0.2252, -0.0233,  0.0483, -0.0495,  0.1313, -0.0061, -0.2159,
          0.2050,  0.1124, -0.0546,  0.0292, -0.2218,  

## Updating the weights manually
Now that you know how to access weights and biases, you will manually perform the job of the PyTorch optimizer. While PyTorch automates this, practicing it manually helps you build intuition for how models learn and adjust. This understanding will be valuable when debugging or fine-tuning neural networks.

A neural network of three layers has been created and stored as the model variable. This network has been used for a forward pass and the loss and its derivatives have been calculated. A default learning rate, lr, has been chosen to scale the gradients when performing the update.

Instructions 1/2
50 XP
1
2
Create the gradient variables by accessing the local gradients of each weight tensor.

In [29]:
weight0 = model[0].weight
weight1 = model[1].weight
weight2 = model[2].weight

# Access the gradients of the weight of each linear layer
grads0 = weight0.grad
grads1 = weight1.grad
grads2 = weight2.grad

Instructions 2/2
50 XP
2
Update the weights using the gradients scaled by the learning rate.

In [33]:
lr = 0.01  # Define a learning rate

# Update the weights using the learning rate and the gradients
weight0 = weight0 - lr * grads0
weight1 = weight1 - lr * grads1
weight2 = weight2 - lr * grads2

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

## Using the PyTorch optimizer
Earlier, you manually updated the weight of a network, gaining insight into how training works behind the scenes. However, this method isn’t scalable for deep networks with many layers.

Thankfully, PyTorch provides the SGD optimizer, which automates this process efficiently in just a few lines of code. Now, you’ll complete the training loop by updating the weights using a PyTorch optimizer.

A neural network has been created and provided as the model variable. This model was used to run a forward pass and create the tensor of predictions pred. The one-hot encoded tensor is named target and the cross entropy loss function is stored as criterion.

torch.optim as optim, and torch.nn as nn have already been loaded for you.

Use optim to create an SGD optimizer with a learning rate of your choice (must be less than one) for the model provided.

In [34]:
import torch.optim as optim

# Create the optimizer
optimizer = optim.SGD(model.parameters(), lr=0.01)

Update the model's parameters using the optimizer.

In [36]:
pred = model(torch.randn(16))  # Example input tensor
target = torch.tensor([1])  # Example target tensor

loss = criterion(pred, target)
loss.backward()

# Update the model's parameters using the optimizer
optimizer.step()

RuntimeError: size mismatch (got input: [2], target: [1])

# Training a Neural Network with PyTorch

Now that you've learned the key components of a neural network, you'll train one using a training loop. You'll explore potential issues like vanishing gradients and learn strategies to address them, such as alternative activation functions and tuning learning rate and momentum.